name = "Timeout"
uuid = "54e99f34-3453-587b-ab13-918c49922018"
license = "MIT"
author = ["Alex Arslan"]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "1.4"